# Generated by Django 6.0.5 on 2026-05-17 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('authors', models.JSONField(default=list)),
                ('description', models.TextField(blank=True, null=True)),
                ('personal_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('want_to_read', 'Want to read'), ('reading', 'Reading'), ('read', 'Read'), ('paused', 'Paused'), ('dnf', 'Did not finish')], default='want_to_read', max_length=50)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('finished_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
